server:
  port: 8080

spring:

  datasource:
    url: jdbc:h2:file:./db
    username: u
    password:

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
